### ISSUE TITLE
The selector labels use an inconsistent naming system. 

### ISSUE THREAD

**Issue by WimTeuling** [Kinakopan/WK03site#16]
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L152

Don’t mix camel case, dash dividers, and so on, without a good system in mind. For example, the BEM method keeps a very strict rule set in regards to naming dividers.

**Comment by Baaam0** [comment]
Changed all <@__subHeading> labels to <@__desc>.
