### ISSUE TITLE
Heading classes are too specific and use varying selector label rules

### ISSUE THREAD

**Issue by WimTeuling** [Kinakopan/WK03site#17]
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L112
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L119
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L129
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L151
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L172
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L188
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L199
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L206

...and so on.

Some use different selector naming rules, others are so specifically linked to the container structure, that I wonder why you would go that far. 

Consider how specific you actually need your class names to be.

For example, the subheadings for all main sections are identical. Why use class names that refer to them specifically? That only complicates restyling later. 
So instead of 
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L119
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L151
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L199
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L256

Why not just write
`<h3 class="section__heading">`

Two advantages:
1) one class affect all section headings
2) it is possible to re-use the h3 for other headings as well. Otherwise, as you are doing it, you would have to write a general h3 tag rule to affect all h3 tags and style them the same. It is more work.

**Comment by Baaam0** [comment]
All h3 class names changed to class="section__heading"

h4 
-  h4 class="list__heading" 
-  h4 class="list__heading-date"
-  h4 class="box__heading"
because these h4 tags are same font style and size but different place
