### ISSUE TITLE
ID selectors used.

### ISSUE THREAD

**Issue by WimTeuling** [Kinakopan/WK03site#19]
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L80

Check that ID selectors are used only for fragment identifiers or javascript hooks. ID selectors are best avoided aside from these two cases.

Your code is also internally inconsistent: in other code sections classes are used to specifically indicate content items. 

And this slider cannot be reused on the same page, if that is deemed necessary.

**Comment by Kinakopan** [comment]
Deleted ID and replaced codes as suggested
