### ISSUE TITLE
Unclear class name

### ISSUE THREAD

**Issue by WimTeuling** [Kinakopan/WK03site#20]
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L35
https://github.com/Kinakopan/WK03site/blob/733f96ae135f66f8bfd85a74fad840bd65d1eab7/index.html#L78

What does spOnly and pcOnly stand for? They use an inconsistent class labeling using camel case as well.

If pcOnly stands for PC only - rethink. Better would be show-for-large and show-for-small-only, for example.

**Comment by Kinakopan** [comment]
Changed spOnly and pcOnly and changed slider's picture's name
